name: mlflow-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pandas==2.2.2
  - numpy==1.26.4
  - scikit-learn==1.6.1
  - mlflow==2.22.0
  - psutil
  - pip:
    - mlflow
