name: mlflow-env
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10
  - pip             # conda akan menginstal pip
  - pandas=2.2.2
  - numpy=1.26.4
  - scikit-learn=1.6.1
  - psutil          # bisa diinstal via conda
  - pip:
      - mlflow==2.22.0
