name: CI - MLflow Project (Python Run)

permissions:
  contents: write

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  run-mlflow-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.10
          activate-environment: mlflow-env
          environment-file: MLProject/conda.yaml

      - name: Install dependencies tambahan
        shell: bash -l {0}
        run: |
          conda activate mlflow-env
          pip install mlflow

      - name: Jalankan skrip modelling.py
        shell: bash -l {0}
        run: |
          conda activate mlflow-env
          python MLProject/modelling.py \
            --input MLProject/namadataset_preprocessing/Automobile_clean.csv \
            --output artifacts/model

      - name: Periksa isi artifacts
        shell: bash -l {0}
        run: |
          echo "=== LIST ARTIFAKS ==="
          ls -R artifacts


      - name: Upload artefak model
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: artifacts/model
