name: CI - MLflow Project

permissions:
  contents: write

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  run-mlflow-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.10
          activate-environment: mlflow-env
          environment-file: MLProject/conda.yaml

      - name: Install MLflow
        shell: bash -l {0}
        run: |
          pip install mlflow

      - name: Jalankan MLflow Project
        shell: bash -l {0}
        run: |
          conda activate mlflow-env
          mlflow run MLProject \
            -P input_data=MLProject/namadataset_preprocessing/Automobile_clean.csv \
            -P output_model_path=MLProject/artifacts/model

      - name: Salin artefak ke folder upload
        run: |
          mkdir -p artifacts/model
          cp -r MLProject/artifacts/model/* artifacts/model/

      - name: Upload artefak model
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: artifacts/model
